version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: .
    volumes:
      - type: bind
        source: ./
        target: /var/www/html/
    ports:
      - 8004:80


  php-mysql-environment:
    container_name: php-mysql
    image: mysql:oracle
    volumes:
      - homepage_mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: php-environment
volumes:
  homepage_mysql: